# Generated by Django 5.2.15 on 2026-07-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_status',
            field=models.CharField(choices=[('not_applicable', 'بدون پیک (تحویل حضوری)'), ('pending', 'در جستجوی پیک'), ('moving_to_store', 'پیک در مسیر فروشگاه'), ('at_store', 'پیک در فروشگاه (در حال دریافت)'), ('moving_to_customer', 'پیک در مسیر مقصد')], default='not_assigned', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'در انتظار تایید فروشگاه'), ('preparing', 'در حال آماده\u200cسازی سفارش'), ('ready', 'آماده تحویل (منتظر پیک یا مشتری)'), ('completed', 'تکمیل و تحویل شده'), ('canceled', 'لغو شده')], default='waiting', max_length=20),
        ),
    ]
